name: Credibility Assessment Level 0

on:
  workflow_call:

jobs:
  check-spdx-headers:
    name: SPDX License Check
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: enarx/spdx@master
      with:
        licenses: Apache-2.0 BSD-3-Clause BSD-2-Clause MIT MPL-2.0
