name: Markdown Linter

on:
  workflow_call:

jobs:
  markdown-lint:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: markdown-lint
      uses: articulate/actions-markdownlint@v1
      with:
        config: .github/workflows/markdownlint.json