name: SRMD Validator

on:
  workflow_call:

jobs:
  srmd-validator:
    name: SRMD Validator
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get SRMD Validator
      run: git clone https://github.com/openMSL/sl-5-1-srmd-validator.git

    - name: Init Submodules
      working-directory: sl-5-1-srmd-validator
      run: git submodule update --init --recursive

    - name: Install Dependencies
      run: pip3 install xmlschema

    - name: Validate SRMD
      working-directory: sl-5-1-srmd-validator
      run: python3 srmd-validator.py

    - name: Commit ID
      working-directory: sl-5-1-srmd-validator
      run: |
        echo "Commit ID: "
        echo $(git rev-parse --short HEAD)
